{
 "title": "Trabalho 01",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de reclamações por trimestre no ano de 2021",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CAST(SUBSTRING(TRIM(TRIMESTRE),1,1) AS FLOAT) as \"time\",\r\n    SUM(CAST(TRIM(QUANTIDADE_DE_RECLAMACOES_REGULADAS_PROCEDENTES) AS FLOAT)) AS QUANTIDADE_DE_RECLAMACOES_REGULADAS_PROCEDENTES,\r\n    SUM(CAST(TRIM(QUANTIDADE_DE_RECLAMACAOES_REGULADAS_OUTRAS) AS FLOAT)) AS QUANTIDADE_DE_RECLAMACAOES_REGULADAS_OUTRAS,\r\n    SUM(CAST(TRIM(QUANTIDADE_DE_RECLAMACOES_NAO_REGULADAS) AS FLOAT)) AS QUANTIDADE_DE_RECLAMACOES_NAO_REGULADAS\r\nFROM\r\n    DW.FT_INDICE_RECLAMACAO\r\nWHERE\r\n    TRIM(ANO) = \"2021\"\r\nGROUP BY \r\n    SUBSTRING(TRIM(TRIMESTRE),1,1)\r\nORDER BY  \r\n    SUBSTRING(TRIM(TRIMESTRE),1,1);"
    }
   ]
  },
  {
   "title": "Somatório do valor das tarifas por ano.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ANO,\r\n    SUM(CAST(TRIM(VALORMAXIMOTOTAL) AS FLOAT)) AS VALOR_TARIFA_MAXIMO\r\nFROM\r\n    DW.FT_INDICE_RECLAMACAO\r\nGROUP BY \r\n    ANO\r\nORDER BY \r\n    ANO;"
    }
   ]
  },
  {
   "title": "Quantidade de clientes, por trimestre, CCS vs SCR no ano de 2021 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n    CAST(SUBSTRING(TRIM(TRIMESTRE),1,1) AS FLOAT) as \"time\",\r\n    SUM(CAST(TRIM(QUANTIDADE_DE_CLIENTES_CCS) AS FLOAT)) AS QUANTIDADE_DE_CLIENTES_CCS,\r\n    SUM(CAST(TRIM(QUANTIDADE_DE_CLIENTES_SCR) AS FLOAT)) AS QUANTIDADE_DE_CLIENTES_SCR\r\nFROM\r\n    DW.FT_INDICE_RECLAMACAO\r\nWHERE\r\n    TRIM(ANO) = \"2021\"\r\nGROUP BY \r\n    SUBSTRING(TRIM(TRIMESTRE),1,1)\r\nORDER BY  \r\n    SUBSTRING(TRIM(TRIMESTRE),1,1);"
    }
   ]
  }
 ]
}